[phases.setup]
nixPkgs = ["ffmpeg"]
aptPkgs = ["ffmpeg"]

[phases.install]
cmds = [
  "apt-get update || true",
  "apt-get install -y ffmpeg || true",
  "pip install -r requirements.txt"
]

[start]
cmd = "python main_final.py"


